---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ibi-config-crb
subjects:
  - kind: ServiceAccount
    name: ibi-config
    namespace: ibi-post-config
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
