apiVersion: ingressnodefirewall.openshift.io/v1alpha1
kind: IngressNodeFirewall
metadata:
  name: ingressnodefirewall
spec:
  interfaces:
  - ens33
  nodeSelector:
    matchLabels:
      edge.io/firewall: 'true' 
  ingress:
  - sourceCIDRs:
      - 0.0.0.0/0 
    rules:
    - order: 10
      protocolConfig:
        protocol: TCP
        tcp:
          ports: 22
      action: Deny
