apiVersion: v1                    
kind: Namespace
metadata:
  name: <clusterName> 
---
apiVersion: cluster.open-cluster-management.io/v1
kind: ManagedCluster
metadata:
  name: <clusterName>
  labels:
    name: <clusterName>
    cloud: auto-detect
    vendor: auto-detect
    cluster.open-cluster-management.io/clusterset: default
  annotations: {}
spec:
  hubAcceptsClient: true
---
apiVersion: agent.open-cluster-management.io/v1
kind: KlusterletAddonConfig
metadata:
  name: <clusterName>
  namespace: <clusterName>
spec:
  clusterName: <clusterName>
  clusterNamespace: <clusterName>
  clusterLabels:
    name: <clusterName>
    cloud: auto-detect
    vendor: auto-detect
    cluster.open-cluster-management.io/clusterset: default
  applicationManager:
    enabled: true
  policyController:
    enabled: true
  searchCollector:
    enabled: true
  certPolicyController:
    enabled: true
